### ISSUE TITLE
Many figs could not be recognized and displayed normally in "All Images"

### ISSUE THREAD

**Issue by sbkk000** [volatile-static/Chartero#19]
Using chartero's all images function in zotero6' s default pdf reader, we found that many figures could not be recognized and displayed normally (non-scanned pdf).

**Comment by volatile-static** [comment]
> Using chartero's all images function in zotero6' s default pdf reader, we found that many figures could not be recognized and displayed normally (non-scanned pdf).

Due to restriction of proformance, there're 3 rules about rendering images currently.
1. If the firest 10 page each has only one image which the same width-height ratio as the page, rendering will stop.
2.  If there are more than 20 images in one page, this page will be skipped.
3. All rendering stops after adding about 100 images.
