### ISSUE TITLE
Can't install on Zotero 6.0.30 for Mac

### ISSUE THREAD

**Issue by abzhaobo** [volatile-static/Chartero#76]
The usual installation procedure leads to "The add-on "%S" could not be installed. It may be incompatible with this version of Zotero." I'm using Zotero 6.0.30 for Mac. 

I'm a bit confused by the note "For legacy Zotero 6 version, please check out [this branch](https://github.com/volatile-static/Chartero/tree/js_overlay)" in the readme. Does it mean that the pure JS branch is valid for Zotero 6, which is the newest version of Zotero, while the latest release of Chartero is only valid for old versions of Zotero? I'm quite confused. When I enter that pure JS branch, I can't not find a valid release as well. Sorry if I missed anything important unintentionally.

**Comment by volatile-static** [comment]
Chartero won't support Zotero6 from version 2.0.0.
The latest release of Chartero supports the [beta build Zotero](https://forums.zotero.org/discussion/105094) only.
Since Zotero7 is going to be released soon, we called Zotero6 "legacy".
You can download the last (also latest) version for Zotero6 at: https://github.com/volatile-static/Chartero/releases/tag/1.3.3

**Comment by abzhaobo** [comment]
> Chartero won't support Zotero6 from version 2.0.0. The latest release of Chartero supports the [beta build Zotero](https://forums.zotero.org/discussion/105094) only. Since Zotero7 is going to be released soon, we called Zotero6 "legacy". You can download the last (also latest) version for Zotero6 at: https://github.com/volatile-static/Chartero/releases/tag/1.3.3

I see. Thanks!
